g:
cd G:\MoSIFT\SiftMotionFFmpeg\
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_1.avi F:\VideoDataset\ActionMovies\newFights\fi_1.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_2.avi F:\VideoDataset\ActionMovies\newFights\fi_2.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_3.avi F:\VideoDataset\ActionMovies\newFights\fi_3.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_4.avi F:\VideoDataset\ActionMovies\newFights\fi_4.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_5.avi F:\VideoDataset\ActionMovies\newFights\fi_5.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_6.avi F:\VideoDataset\ActionMovies\newFights\fi_6.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_7.avi F:\VideoDataset\ActionMovies\newFights\fi_7.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_8.avi F:\VideoDataset\ActionMovies\newFights\fi_8.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_9.avi F:\VideoDataset\ActionMovies\newFights\fi_9.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_10.avi F:\VideoDataset\ActionMovies\newFights\fi_10.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_11.avi F:\VideoDataset\ActionMovies\newFights\fi_11.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_12.avi F:\VideoDataset\ActionMovies\newFights\fi_12.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_13.avi F:\VideoDataset\ActionMovies\newFights\fi_13.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_14.avi F:\VideoDataset\ActionMovies\newFights\fi_14.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_15.avi F:\VideoDataset\ActionMovies\newFights\fi_15.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_16.avi F:\VideoDataset\ActionMovies\newFights\fi_16.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_17.avi F:\VideoDataset\ActionMovies\newFights\fi_17.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_18.avi F:\VideoDataset\ActionMovies\newFights\fi_18.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_19.avi F:\VideoDataset\ActionMovies\newFights\fi_19.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_20.avi F:\VideoDataset\ActionMovies\newFights\fi_20.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_21.avi F:\VideoDataset\ActionMovies\newFights\fi_21.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_22.avi F:\VideoDataset\ActionMovies\newFights\fi_22.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_23.avi F:\VideoDataset\ActionMovies\newFights\fi_23.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_24.avi F:\VideoDataset\ActionMovies\newFights\fi_24.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_25.avi F:\VideoDataset\ActionMovies\newFights\fi_25.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_26.avi F:\VideoDataset\ActionMovies\newFights\fi_26.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_27.avi F:\VideoDataset\ActionMovies\newFights\fi_27.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_28.avi F:\VideoDataset\ActionMovies\newFights\fi_28.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_29.avi F:\VideoDataset\ActionMovies\newFights\fi_29.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_30.avi F:\VideoDataset\ActionMovies\newFights\fi_30.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_31.avi F:\VideoDataset\ActionMovies\newFights\fi_31.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_32.avi F:\VideoDataset\ActionMovies\newFights\fi_32.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_33.avi F:\VideoDataset\ActionMovies\newFights\fi_33.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_34.avi F:\VideoDataset\ActionMovies\newFights\fi_34.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_35.avi F:\VideoDataset\ActionMovies\newFights\fi_35.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_36.avi F:\VideoDataset\ActionMovies\newFights\fi_36.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_37.avi F:\VideoDataset\ActionMovies\newFights\fi_37.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_38.avi F:\VideoDataset\ActionMovies\newFights\fi_38.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_39.avi F:\VideoDataset\ActionMovies\newFights\fi_39.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_40.avi F:\VideoDataset\ActionMovies\newFights\fi_40.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_41.avi F:\VideoDataset\ActionMovies\newFights\fi_41.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_42.avi F:\VideoDataset\ActionMovies\newFights\fi_42.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_43.avi F:\VideoDataset\ActionMovies\newFights\fi_43.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_44.avi F:\VideoDataset\ActionMovies\newFights\fi_44.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_45.avi F:\VideoDataset\ActionMovies\newFights\fi_45.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_46.avi F:\VideoDataset\ActionMovies\newFights\fi_46.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_47.avi F:\VideoDataset\ActionMovies\newFights\fi_47.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_48.avi F:\VideoDataset\ActionMovies\newFights\fi_48.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_49.avi F:\VideoDataset\ActionMovies\newFights\fi_49.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_50.avi F:\VideoDataset\ActionMovies\newFights\fi_50.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_51.avi F:\VideoDataset\ActionMovies\newFights\fi_51.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_52.avi F:\VideoDataset\ActionMovies\newFights\fi_52.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_53.avi F:\VideoDataset\ActionMovies\newFights\fi_53.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_54.avi F:\VideoDataset\ActionMovies\newFights\fi_54.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_55.avi F:\VideoDataset\ActionMovies\newFights\fi_55.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_56.avi F:\VideoDataset\ActionMovies\newFights\fi_56.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_57.avi F:\VideoDataset\ActionMovies\newFights\fi_57.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_58.avi F:\VideoDataset\ActionMovies\newFights\fi_58.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_59.avi F:\VideoDataset\ActionMovies\newFights\fi_59.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_60.avi F:\VideoDataset\ActionMovies\newFights\fi_60.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_61.avi F:\VideoDataset\ActionMovies\newFights\fi_61.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_62.avi F:\VideoDataset\ActionMovies\newFights\fi_62.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_63.avi F:\VideoDataset\ActionMovies\newFights\fi_63.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_64.avi F:\VideoDataset\ActionMovies\newFights\fi_64.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_65.avi F:\VideoDataset\ActionMovies\newFights\fi_65.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_66.avi F:\VideoDataset\ActionMovies\newFights\fi_66.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_67.avi F:\VideoDataset\ActionMovies\newFights\fi_67.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_68.avi F:\VideoDataset\ActionMovies\newFights\fi_68.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_69.avi F:\VideoDataset\ActionMovies\newFights\fi_69.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_70.avi F:\VideoDataset\ActionMovies\newFights\fi_70.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_71.avi F:\VideoDataset\ActionMovies\newFights\fi_71.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_72.avi F:\VideoDataset\ActionMovies\newFights\fi_72.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_73.avi F:\VideoDataset\ActionMovies\newFights\fi_73.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_74.avi F:\VideoDataset\ActionMovies\newFights\fi_74.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_75.avi F:\VideoDataset\ActionMovies\newFights\fi_75.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_76.avi F:\VideoDataset\ActionMovies\newFights\fi_76.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_77.avi F:\VideoDataset\ActionMovies\newFights\fi_77.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_78.avi F:\VideoDataset\ActionMovies\newFights\fi_78.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_79.avi F:\VideoDataset\ActionMovies\newFights\fi_79.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_80.avi F:\VideoDataset\ActionMovies\newFights\fi_80.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_81.avi F:\VideoDataset\ActionMovies\newFights\fi_81.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_82.avi F:\VideoDataset\ActionMovies\newFights\fi_82.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_83.avi F:\VideoDataset\ActionMovies\newFights\fi_83.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_84.avi F:\VideoDataset\ActionMovies\newFights\fi_84.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_85.avi F:\VideoDataset\ActionMovies\newFights\fi_85.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_86.avi F:\VideoDataset\ActionMovies\newFights\fi_86.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_87.avi F:\VideoDataset\ActionMovies\newFights\fi_87.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_88.avi F:\VideoDataset\ActionMovies\newFights\fi_88.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_89.avi F:\VideoDataset\ActionMovies\newFights\fi_89.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_90.avi F:\VideoDataset\ActionMovies\newFights\fi_90.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_91.avi F:\VideoDataset\ActionMovies\newFights\fi_91.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_92.avi F:\VideoDataset\ActionMovies\newFights\fi_92.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_93.avi F:\VideoDataset\ActionMovies\newFights\fi_93.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_94.avi F:\VideoDataset\ActionMovies\newFights\fi_94.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_95.avi F:\VideoDataset\ActionMovies\newFights\fi_95.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_96.avi F:\VideoDataset\ActionMovies\newFights\fi_96.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_97.avi F:\VideoDataset\ActionMovies\newFights\fi_97.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_98.avi F:\VideoDataset\ActionMovies\newFights\fi_98.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_99.avi F:\VideoDataset\ActionMovies\newFights\fi_99.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\newFights\fi_100.avi F:\VideoDataset\ActionMovies\newFights\fi_100.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\1.mpg F:\VideoDataset\ActionMovies\nofights\no_1.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\2.mpg F:\VideoDataset\ActionMovies\nofights\no_2.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\3.mpg F:\VideoDataset\ActionMovies\nofights\no_3.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\4.mpg F:\VideoDataset\ActionMovies\nofights\no_4.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\5.mpg F:\VideoDataset\ActionMovies\nofights\no_5.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\6.mpg F:\VideoDataset\ActionMovies\nofights\no_6.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\7.mpg F:\VideoDataset\ActionMovies\nofights\no_7.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\8.mpg F:\VideoDataset\ActionMovies\nofights\no_8.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\9.mpg F:\VideoDataset\ActionMovies\nofights\no_9.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\10.mpg F:\VideoDataset\ActionMovies\nofights\no_10.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\11.mpg F:\VideoDataset\ActionMovies\nofights\no_11.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\12.mpg F:\VideoDataset\ActionMovies\nofights\no_12.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\13.mpg F:\VideoDataset\ActionMovies\nofights\no_13.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\14.mpg F:\VideoDataset\ActionMovies\nofights\no_14.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\15.mpg F:\VideoDataset\ActionMovies\nofights\no_15.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\16.mpg F:\VideoDataset\ActionMovies\nofights\no_16.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\17.mpg F:\VideoDataset\ActionMovies\nofights\no_17.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\18.mpg F:\VideoDataset\ActionMovies\nofights\no_18.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\19.mpg F:\VideoDataset\ActionMovies\nofights\no_19.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\20.mpg F:\VideoDataset\ActionMovies\nofights\no_20.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\21.mpg F:\VideoDataset\ActionMovies\nofights\no_21.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\22.mpg F:\VideoDataset\ActionMovies\nofights\no_22.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\23.mpg F:\VideoDataset\ActionMovies\nofights\no_23.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\24.mpg F:\VideoDataset\ActionMovies\nofights\no_24.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\25.mpg F:\VideoDataset\ActionMovies\nofights\no_25.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\26.mpg F:\VideoDataset\ActionMovies\nofights\no_26.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\27.mpg F:\VideoDataset\ActionMovies\nofights\no_27.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\28.mpg F:\VideoDataset\ActionMovies\nofights\no_28.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\29.mpg F:\VideoDataset\ActionMovies\nofights\no_29.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\30.mpg F:\VideoDataset\ActionMovies\nofights\no_30.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\31.mpg F:\VideoDataset\ActionMovies\nofights\no_31.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\32.mpg F:\VideoDataset\ActionMovies\nofights\no_32.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\33.mpg F:\VideoDataset\ActionMovies\nofights\no_33.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\34.mpg F:\VideoDataset\ActionMovies\nofights\no_34.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\35.mpg F:\VideoDataset\ActionMovies\nofights\no_35.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\36.mpg F:\VideoDataset\ActionMovies\nofights\no_36.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\37.mpg F:\VideoDataset\ActionMovies\nofights\no_37.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\38.mpg F:\VideoDataset\ActionMovies\nofights\no_38.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\39.mpg F:\VideoDataset\ActionMovies\nofights\no_39.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\40.mpg F:\VideoDataset\ActionMovies\nofights\no_40.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\41.mpg F:\VideoDataset\ActionMovies\nofights\no_41.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\42.mpg F:\VideoDataset\ActionMovies\nofights\no_42.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\43.mpg F:\VideoDataset\ActionMovies\nofights\no_43.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\44.mpg F:\VideoDataset\ActionMovies\nofights\no_44.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\45.mpg F:\VideoDataset\ActionMovies\nofights\no_45.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\46.mpg F:\VideoDataset\ActionMovies\nofights\no_46.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\47.mpg F:\VideoDataset\ActionMovies\nofights\no_47.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\48.mpg F:\VideoDataset\ActionMovies\nofights\no_48.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\49.mpg F:\VideoDataset\ActionMovies\nofights\no_49.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\50.mpg F:\VideoDataset\ActionMovies\nofights\no_50.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\51.mpg F:\VideoDataset\ActionMovies\nofights\no_51.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\52.mpg F:\VideoDataset\ActionMovies\nofights\no_52.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\53.mpg F:\VideoDataset\ActionMovies\nofights\no_53.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\54.mpg F:\VideoDataset\ActionMovies\nofights\no_54.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\55.mpg F:\VideoDataset\ActionMovies\nofights\no_55.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\56.mpg F:\VideoDataset\ActionMovies\nofights\no_56.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\57.mpg F:\VideoDataset\ActionMovies\nofights\no_57.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\58.mpg F:\VideoDataset\ActionMovies\nofights\no_58.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\59.mpg F:\VideoDataset\ActionMovies\nofights\no_59.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\60.mpg F:\VideoDataset\ActionMovies\nofights\no_60.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\61.mpg F:\VideoDataset\ActionMovies\nofights\no_61.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\62.mpg F:\VideoDataset\ActionMovies\nofights\no_62.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\63.mpg F:\VideoDataset\ActionMovies\nofights\no_63.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\64.mpg F:\VideoDataset\ActionMovies\nofights\no_64.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\65.mpg F:\VideoDataset\ActionMovies\nofights\no_65.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\66.mpg F:\VideoDataset\ActionMovies\nofights\no_66.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\67.mpg F:\VideoDataset\ActionMovies\nofights\no_67.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\68.mpg F:\VideoDataset\ActionMovies\nofights\no_68.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\69.mpg F:\VideoDataset\ActionMovies\nofights\no_69.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\70.mpg F:\VideoDataset\ActionMovies\nofights\no_70.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\71.mpg F:\VideoDataset\ActionMovies\nofights\no_71.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\72.mpg F:\VideoDataset\ActionMovies\nofights\no_72.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\73.mpg F:\VideoDataset\ActionMovies\nofights\no_73.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\74.mpg F:\VideoDataset\ActionMovies\nofights\no_74.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\75.mpg F:\VideoDataset\ActionMovies\nofights\no_75.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\76.mpg F:\VideoDataset\ActionMovies\nofights\no_76.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\77.mpg F:\VideoDataset\ActionMovies\nofights\no_77.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\78.mpg F:\VideoDataset\ActionMovies\nofights\no_78.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\79.mpg F:\VideoDataset\ActionMovies\nofights\no_79.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\80.mpg F:\VideoDataset\ActionMovies\nofights\no_80.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\81.mpg F:\VideoDataset\ActionMovies\nofights\no_81.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\82.mpg F:\VideoDataset\ActionMovies\nofights\no_82.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\83.mpg F:\VideoDataset\ActionMovies\nofights\no_83.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\84.mpg F:\VideoDataset\ActionMovies\nofights\no_84.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\85.mpg F:\VideoDataset\ActionMovies\nofights\no_85.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\86.mpg F:\VideoDataset\ActionMovies\nofights\no_86.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\87.mpg F:\VideoDataset\ActionMovies\nofights\no_87.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\88.mpg F:\VideoDataset\ActionMovies\nofights\no_88.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\89.mpg F:\VideoDataset\ActionMovies\nofights\no_89.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\90.mpg F:\VideoDataset\ActionMovies\nofights\no_90.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\91.mpg F:\VideoDataset\ActionMovies\nofights\no_91.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\92.mpg F:\VideoDataset\ActionMovies\nofights\no_92.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\93.mpg F:\VideoDataset\ActionMovies\nofights\no_93.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\94.mpg F:\VideoDataset\ActionMovies\nofights\no_94.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\95.mpg F:\VideoDataset\ActionMovies\nofights\no_95.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\96.mpg F:\VideoDataset\ActionMovies\nofights\no_96.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\97.mpg F:\VideoDataset\ActionMovies\nofights\no_97.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\98.mpg F:\VideoDataset\ActionMovies\nofights\no_98.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\99.mpg F:\VideoDataset\ActionMovies\nofights\no_99.txt
SiftMotionFFmpeg.exe F:\VideoDataset\ActionMovies\nofights\100.mpg F:\VideoDataset\ActionMovies\nofights\no_100.txt
